print ("-----------------------------------")
print ("tugas 1 SISOP kelas-B")
print ("-----------------------------------")
print ("nama: muizzadin")
print ("NPM: 21083010116")
print ("-----------------------------------")
print ("notes:")
print ("-----------------------------------")
print ("Halo dunia!")
print ("ini adalah skrip bash pertamaku di linux")
